### PR TITLE
Support for class names

### PR DESCRIPTION
**Pull request by seahindeniz**
In some cases, there should be a choice for adding class names to generated elements like "containerClass". 

Therefore I've changed some lines regarding the need

### CODE REVIEW

**Comment by nagaozen** [comment]
Hi @seahindeniz, thanks for the PR! Could you just explain further why it's better to `.listClass` instead of `.user-content-toc ol`, `.listElementClass` instead of `.user-content-toc li` and so on?

**Comment by seahindeniz** [comment]
Well, in my case, I'm using a additional way to style elements and this kind of libraries has their pre-defined styles for html elements. That is why I thought this is a good way to implement names easily

**Comment by nagaozen** [comment]
hi @seahindeniz, I've published the updated version `3.0.0` with your changes, but a different classname for the item. Instead of `listElementClass` it is `itemClass`.

Thanks for the PR.

**Comment by seahindeniz** [comment]
Awesome, thank you! @nagaozen

**Pull request merged**
